apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydeploy
    app.kubernetes.io/instance: myproject
  name: mydeploy
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: mydeploy
  type: NodePort
status:
  loadBalancer: {}
