apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: my-svc
    namespace: default
spec:
  type: NodePort
  selector:
    app: mydp
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080
      nodePort: 30007 
